### ISSUE TITLE
KeyError: 'Efficiency' when updating matched dataset

### ISSUE THREAD

**Issue by ChinCity** [PyPSA/powerplantmatching#29]
After integrating the dataset in data.py. 

I ran 

     pm.powerplants(update_all=True)

And got the following error:

    INFO:powerplantmatching.collection:Collect combined dataset for CARMA, ENTSOE, GEO, GPD, JRC, 
    JRC_OPEN_update, OPSD
    INFO:numexpr.utils:NumExpr defaulting to 4 threads.
    INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'CARMA'.
    WARNING:powerplantmatching.core:Geoparsing not possible as no google api key was found, please add 
    the key to your config.yaml if you want to enable it.
    INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'ENTSOE'.
    INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'GEO'.
    INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'GPD'.
    INFO:powerplantmatching.cleaning:Aggregating blocks to entire units in 'JRC'.
    Traceback (most recent call last):
    
      File "<ipython-input-5-2737e403b9c0>", line 1, in <module>
        pm.powerplants(update_all=True)
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\collection.py", line 213, in matched_data
        matched = collect(matching_sources, **collection_kwargs)
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\collection.py", line 99, in collect
        dfs = parmap(df_by_name, datasets)
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\utils.py", line 364, in parmap
        return list(map(f, arg_list))
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\collection.py", line 75, in df_by_name
        config=config)
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\cleaning.py", line 281, in aggregate_units
        df = (df.assign(**{col: df[col] * df.Capacity for col in weighted_cols})
    
      File "c:\users\sab\desktop\powerplantmatching-0.4.1\powerplantmatching-0.4.1\powerplantmatching\cleaning.py", line 281, in <dictcomp>
        df = (df.assign(**{col: df[col] * df.Capacity for col in weighted_cols})
    
      File "C:\Users\sab\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 2917, in __getitem__
        indexer = self.columns.get_loc(key)
    
      File "C:\Users\sab\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2604, in get_loc
        return self._engine.get_loc(self._maybe_cast_indexer(key))
    
      File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
    
      File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
    
      File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
      File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
    KeyError: 'Efficiency'

**Comment by FabianHofmann** [comment]
Very likely fixed by right now, please reopen if it still remains
